### ISSUE TITLE
comp_pe() error

### ISSUE THREAD

**Issue by icsabai** [dinner-group/SubFormer#1]
In the current version in subformer/utils/pe.py  comp_pe() returns only the eigenvectors. 
In subformer/utils/transform.py at line 117 and 133 two return values are expected:
data.graph_lpe,data.graph_product = comp_pe(...)

graph_product is not provided by comp_pe(...) as far as I can see.

Similar problem with comp_spa() lines 126, 148, it also returns only the eigenvectors, no "sp_product".

Maybe subformer/utils/pe.py is an outdated version?

**Comment by zpengmei** [comment]
Hi icsabai,

Sorry for the late reply, just got noticed. I am actually cleaning up the code and planning to update the repo along with the formal draft. We will fix this soon!

Thanks,
Zihan

**Comment by zpengmei** [comment]
Hi icsabai, 

May you check out my repo here? https://github.com/zpengmei/SubFormer-Spec 
I just checked the code which should be working. This repo also contains our new extension.

Best,
Zihan
